// <auto-generated />
using System;
using FLyTicketService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FLyTicketService.Migrations
{
    [DbContext(typeof(FLyTicketDbContext))]
    partial class FLyTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FLyTicketService.Model.Aircraft", b =>
                {
                    b.Property<Guid>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Model = "Boeing 737-MAX",
                            RegistrationNumber = "SP-LAA"
                        },
                        new
                        {
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Model = "Airbus A320Neo",
                            RegistrationNumber = "SP-LBG"
                        });
                });

            modelBuilder.Entity("FLyTicketService.Model.AircraftSeat", b =>
                {
                    b.Property<Guid>("AircraftSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<bool>("OutOfService")
                        .HasColumnType("bit");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AircraftSeatId");

                    b.HasIndex("AircraftId");

                    b.ToTable("AircraftSeats");

                    b.HasData(
                        new
                        {
                            AircraftSeatId = new Guid("0c72a93a-129c-45b6-8d21-5384a16500d3"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("8c545eee-aed9-4f3d-bc7e-d1575a830892"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("8174c953-f7d9-4062-9192-a5e4c83b0a03"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("46c8fdf1-d07d-4318-bb1c-3472b8c8e29a"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("1733efdf-2341-488b-b14e-506c8b5155ff"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1E"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("508ba879-8d09-44c4-b762-d86ddb802705"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("59efca74-baa3-431f-8151-23935799170c"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("899ffa5c-9128-4c62-9e3b-5199be696bb2"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("06ca6b1a-dc74-485f-ad4c-f4862b828e37"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("cae6e272-8db3-4044-a57b-38fa5248d19b"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2E"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("74f1eea2-2be9-489f-9c24-ea568ed7b8d7"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("70d18860-ae6f-4f07-8207-5da4e8c4f47b"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("20e80335-01cb-4dfb-bfb9-52e05978f20d"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("8102b7fb-55e9-4dab-bc04-cc44f8d590c1"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("6c5b7673-9484-4b0a-b8ca-f29f79806c15"),
                            AircraftId = new Guid("4d50d09f-2fd0-492c-9e3d-05fc1831677e"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "3E"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("f9b7266c-7bfb-4c3a-b5be-3908ba1a79a0"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("2a599a38-7038-4106-8ea9-e3b11a8f1065"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("57744294-340c-46b5-b32a-98b0ba30dd87"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("2cbd9108-ed3c-4ade-ac55-4884df8fdb7b"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("02088211-b948-4244-b1a9-541300c38094"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "1E"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("0a37cefd-cf6d-4815-aacd-cbb9eb88e7da"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("abe2fa3d-e5a0-45eb-afdc-a13e6ad0c87f"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("ff6a2999-c9a4-4f95-91d6-d22a48b5e8e5"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("f671ba9c-63bf-42ed-973f-06acb365eeef"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            AircraftSeatId = new Guid("9c29259b-873c-409c-a40b-4c72ecc7f50b"),
                            AircraftId = new Guid("eadb857d-e038-4ff3-8680-8426e8a5ec4b"),
                            Class = 1,
                            OutOfService = false,
                            SeatNumber = "2E"
                        });
                });

            modelBuilder.Entity("FLyTicketService.Model.Airline", b =>
                {
                    b.Property<Guid>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("AirlineId");

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            AirlineId = new Guid("e9d8196e-ad35-4bbf-97dc-6c1d013dc184"),
                            AirlineName = "Air India",
                            Country = "India",
                            IATA = "AI"
                        },
                        new
                        {
                            AirlineId = new Guid("8f1e36b9-9a5c-4cac-b1d0-9bf654084b58"),
                            AirlineName = "Delta Airlines",
                            Country = "USA",
                            IATA = "DL"
                        },
                        new
                        {
                            AirlineId = new Guid("e29dbd49-8574-4e78-8983-d5bcd9f2f741"),
                            AirlineName = "American Airlines",
                            Country = "USA",
                            IATA = "AA"
                        },
                        new
                        {
                            AirlineId = new Guid("5c0e4717-d08e-4fc2-ac4a-02967b09942e"),
                            AirlineName = "Emirates",
                            Country = "UAE",
                            IATA = "EK"
                        },
                        new
                        {
                            AirlineId = new Guid("f5abe099-90d7-4731-b4c7-0910da1b1db7"),
                            AirlineName = "Qatar Airways",
                            Country = "Qatar",
                            IATA = "QR"
                        },
                        new
                        {
                            AirlineId = new Guid("b0a64a5e-71f6-4296-9b05-0da62da662e8"),
                            AirlineName = "LOT",
                            Country = "Poland",
                            IATA = "LO"
                        });
                });

            modelBuilder.Entity("FLyTicketService.Model.Airport", b =>
                {
                    b.Property<Guid>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Altitude")
                        .HasColumnType("float");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DST")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ICAO")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirportId");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportId = new Guid("a00687bf-90db-43c1-a810-39d3752d4d38"),
                            AirportName = "Hartsfield-Jackson Atlanta International Airport",
                            Altitude = 1026.0,
                            City = "Atlanta",
                            Country = "United States",
                            DST = "A",
                            IATA = "ATL",
                            ICAO = "KATL",
                            Latitude = 33.636699999999998,
                            Longitude = -84.428100000000001,
                            Timezone = "America/New_York"
                        },
                        new
                        {
                            AirportId = new Guid("d48bced6-df68-4d8c-bab5-12ff5b2ea1aa"),
                            AirportName = "Beijing Capital International Airport",
                            Altitude = 116.0,
                            City = "Beijing",
                            Country = "China",
                            DST = "N",
                            IATA = "PEK",
                            ICAO = "ZBAA",
                            Latitude = 40.080100000000002,
                            Longitude = 116.58459999999999,
                            Timezone = "Asia/Shanghai"
                        },
                        new
                        {
                            AirportId = new Guid("d27dae84-d8c2-4ea4-a217-ea51d62988e4"),
                            AirportName = "Los Angeles International Airport",
                            Altitude = 125.0,
                            City = "Los Angeles",
                            Country = "United States",
                            DST = "A",
                            IATA = "LAX",
                            ICAO = "KLAX",
                            Latitude = 33.942500000000003,
                            Longitude = -118.4081,
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            AirportId = new Guid("5678ca70-aecc-4d7b-97e4-d8a4f2b21afa"),
                            AirportName = "O'Hare International Airport",
                            Altitude = 672.0,
                            City = "Chicago",
                            Country = "United States",
                            DST = "A",
                            IATA = "ORD",
                            ICAO = "KORD",
                            Latitude = 41.9786,
                            Longitude = -87.904799999999994,
                            Timezone = "America/Chicago"
                        },
                        new
                        {
                            AirportId = new Guid("052b64a4-4c43-4ad6-a261-527bd1d9763e"),
                            AirportName = "Dallas/Fort Worth International Airport",
                            Altitude = 607.0,
                            City = "Dallas-Fort Worth",
                            Country = "United States",
                            DST = "A",
                            IATA = "DFW",
                            ICAO = "KDFW",
                            Latitude = 32.896799999999999,
                            Longitude = -97.037999999999997,
                            Timezone = "America/Chicago"
                        },
                        new
                        {
                            AirportId = new Guid("c8d49b0f-c357-4a49-9a9e-69894af29d9c"),
                            AirportName = "Denver International Airport",
                            Altitude = 5431.0,
                            City = "Denver",
                            Country = "United States",
                            DST = "A",
                            IATA = "DEN",
                            ICAO = "KDEN",
                            Latitude = 39.861699999999999,
                            Longitude = -104.67310000000001,
                            Timezone = "America/Denver"
                        },
                        new
                        {
                            AirportId = new Guid("670934e4-a1f3-4109-b31f-f23586b7fd70"),
                            AirportName = "John F. Kennedy International Airport",
                            Altitude = 13.0,
                            City = "New York",
                            Country = "United States",
                            DST = "A",
                            IATA = "JFK",
                            ICAO = "KJFK",
                            Latitude = 40.641300000000001,
                            Longitude = -73.778099999999995,
                            Timezone = "America/New_York"
                        },
                        new
                        {
                            AirportId = new Guid("0e0edb20-c0e7-4b09-ab07-a0536d2137df"),
                            AirportName = "San Francisco International Airport",
                            Altitude = 13.0,
                            City = "San Francisco",
                            Country = "United States",
                            DST = "A",
                            IATA = "SFO",
                            ICAO = "KSFO",
                            Latitude = 37.6188,
                            Longitude = -122.375,
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            AirportId = new Guid("dd3bab2b-a2ec-4f86-9373-dc2578c2ca51"),
                            AirportName = "Seattle-Tacoma International Airport",
                            Altitude = 433.0,
                            City = "Seattle",
                            Country = "United States",
                            DST = "A",
                            IATA = "SEA",
                            ICAO = "KSEA",
                            Latitude = 47.450200000000002,
                            Longitude = -122.30880000000001,
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            AirportId = new Guid("bac8f71b-5f45-4774-99d6-e7ccac92f879"),
                            AirportName = "Miami International Airport",
                            Altitude = 8.0,
                            City = "Miami",
                            Country = "United States",
                            DST = "A",
                            IATA = "MIA",
                            ICAO = "KMIA",
                            Latitude = 25.7959,
                            Longitude = -80.287000000000006,
                            Timezone = "America/New_York"
                        },
                        new
                        {
                            AirportId = new Guid("595b9d28-9b8e-4c5a-b7cc-de2b7ef864a0"),
                            AirportName = "Heathrow Airport",
                            Altitude = 83.0,
                            City = "London",
                            Country = "United Kingdom",
                            DST = "E",
                            IATA = "LHR",
                            ICAO = "EGLL",
                            Latitude = 51.470599999999997,
                            Longitude = -0.46189999999999998,
                            Timezone = "Europe/London"
                        },
                        new
                        {
                            AirportId = new Guid("156b135a-364c-467e-89e1-6a019bde6c72"),
                            AirportName = "Charles de Gaulle Airport",
                            Altitude = 392.0,
                            City = "Paris",
                            Country = "France",
                            DST = "E",
                            IATA = "CDG",
                            ICAO = "LFPG",
                            Latitude = 49.009700000000002,
                            Longitude = 2.5478999999999998,
                            Timezone = "Europe/Paris"
                        },
                        new
                        {
                            AirportId = new Guid("f79d4663-9649-4c7c-af47-4b1fd73692b6"),
                            AirportName = "Frankfurt Airport",
                            Altitude = 364.0,
                            City = "Frankfurt",
                            Country = "Germany",
                            DST = "E",
                            IATA = "FRA",
                            ICAO = "EDDF",
                            Latitude = 50.0379,
                            Longitude = 8.5622000000000007,
                            Timezone = "Europe/Berlin"
                        },
                        new
                        {
                            AirportId = new Guid("7e9e97bb-5960-4d8b-b22b-922d8d91e8b2"),
                            AirportName = "Amsterdam Airport Schiphol",
                            Altitude = -11.0,
                            City = "Amsterdam",
                            Country = "Netherlands",
                            DST = "E",
                            IATA = "AMS",
                            ICAO = "EHAM",
                            Latitude = 52.308599999999998,
                            Longitude = 4.7638999999999996,
                            Timezone = "Europe/Amsterdam"
                        },
                        new
                        {
                            AirportId = new Guid("b7ee7109-861d-4016-a5c3-6df7d1faa983"),
                            AirportName = "Adolfo Suárez Madrid–Barajas Airport",
                            Altitude = 1998.0,
                            City = "Madrid",
                            Country = "Spain",
                            DST = "E",
                            IATA = "MAD",
                            ICAO = "LEMD",
                            Latitude = 40.471899999999998,
                            Longitude = -3.5626000000000002,
                            Timezone = "Europe/Madrid"
                        },
                        new
                        {
                            AirportId = new Guid("d24a0bb9-a1e4-48ce-b4e2-0bc42c4dd297"),
                            AirportName = "Leonardo da Vinci–Fiumicino Airport",
                            Altitude = 13.0,
                            City = "Rome",
                            Country = "Italy",
                            DST = "E",
                            IATA = "FCO",
                            ICAO = "LIRF",
                            Latitude = 41.8003,
                            Longitude = 12.238899999999999,
                            Timezone = "Europe/Rome"
                        },
                        new
                        {
                            AirportId = new Guid("30683ffa-c6f5-475e-b45f-ef645d3025fd"),
                            AirportName = "Munich Airport",
                            Altitude = 1487.0,
                            City = "Munich",
                            Country = "Germany",
                            DST = "E",
                            IATA = "MUC",
                            ICAO = "EDDM",
                            Latitude = 48.3538,
                            Longitude = 11.786099999999999,
                            Timezone = "Europe/Berlin"
                        },
                        new
                        {
                            AirportId = new Guid("62a70b00-5b93-476a-9f53-949de2cc7779"),
                            AirportName = "Barcelona–El Prat Airport",
                            Altitude = 12.0,
                            City = "Barcelona",
                            Country = "Spain",
                            DST = "E",
                            IATA = "BCN",
                            ICAO = "LEBL",
                            Latitude = 41.297400000000003,
                            Longitude = 2.0832999999999999,
                            Timezone = "Europe/Madrid"
                        },
                        new
                        {
                            AirportId = new Guid("edfbe350-1c7e-42b6-b891-ed4de257625a"),
                            AirportName = "Istanbul Airport",
                            Altitude = 325.0,
                            City = "Istanbul",
                            Country = "Turkey",
                            DST = "E",
                            IATA = "IST",
                            ICAO = "LTFM",
                            Latitude = 41.275300000000001,
                            Longitude = 28.751899999999999,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            AirportId = new Guid("93dce287-8e28-4084-8fc2-b80b0f6f0263"),
                            AirportName = "Hartsfield-Jackson Atlanta International Airport",
                            Altitude = 1026.0,
                            City = "Atlanta",
                            Country = "United States",
                            DST = "A",
                            IATA = "ATL",
                            ICAO = "KATL",
                            Latitude = 33.636699999999998,
                            Longitude = -84.428100000000001,
                            Timezone = "America/New_York"
                        },
                        new
                        {
                            AirportId = new Guid("62e8885c-3b95-4a2b-a0ef-f83256622823"),
                            AirportName = "Beijing Capital International Airport",
                            Altitude = 116.0,
                            City = "Beijing",
                            Country = "China",
                            DST = "N",
                            IATA = "PEK",
                            ICAO = "ZBAA",
                            Latitude = 40.080100000000002,
                            Longitude = 116.58459999999999,
                            Timezone = "Asia/Shanghai"
                        },
                        new
                        {
                            AirportId = new Guid("1a2f3a19-8196-4e19-a1ee-567af0d2e8f6"),
                            AirportName = "Los Angeles International Airport",
                            Altitude = 125.0,
                            City = "Los Angeles",
                            Country = "United States",
                            DST = "A",
                            IATA = "LAX",
                            ICAO = "KLAX",
                            Latitude = 33.942500000000003,
                            Longitude = -118.4081,
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            AirportId = new Guid("2c65d764-4b4f-4af2-b555-9d8c2503eaab"),
                            AirportName = "O'Hare International Airport",
                            Altitude = 672.0,
                            City = "Chicago",
                            Country = "United States",
                            DST = "A",
                            IATA = "ORD",
                            ICAO = "KORD",
                            Latitude = 41.9786,
                            Longitude = -87.904799999999994,
                            Timezone = "America/Chicago"
                        },
                        new
                        {
                            AirportId = new Guid("85bc5ecb-b957-41a8-b9bd-720b10494ad1"),
                            AirportName = "Dallas/Fort Worth International Airport",
                            Altitude = 607.0,
                            City = "Dallas-Fort Worth",
                            Country = "United States",
                            DST = "A",
                            IATA = "DFW",
                            ICAO = "KDFW",
                            Latitude = 32.896799999999999,
                            Longitude = -97.037999999999997,
                            Timezone = "America/Chicago"
                        },
                        new
                        {
                            AirportId = new Guid("87ed1053-d4c3-47cb-a0bc-dcc15a8a7146"),
                            AirportName = "Denver International Airport",
                            Altitude = 5431.0,
                            City = "Denver",
                            Country = "United States",
                            DST = "A",
                            IATA = "DEN",
                            ICAO = "KDEN",
                            Latitude = 39.861699999999999,
                            Longitude = -104.67310000000001,
                            Timezone = "America/Denver"
                        },
                        new
                        {
                            AirportId = new Guid("59b8349e-3070-4e8d-86d5-e88f7a612b9e"),
                            AirportName = "John F. Kennedy International Airport",
                            Altitude = 13.0,
                            City = "New York",
                            Country = "United States",
                            DST = "A",
                            IATA = "JFK",
                            ICAO = "KJFK",
                            Latitude = 40.641300000000001,
                            Longitude = -73.778099999999995,
                            Timezone = "America/New_York"
                        },
                        new
                        {
                            AirportId = new Guid("7b7010d9-17bb-4a4d-b9e9-aa200aae7ee9"),
                            AirportName = "San Francisco International Airport",
                            Altitude = 13.0,
                            City = "San Francisco",
                            Country = "United States",
                            DST = "A",
                            IATA = "SFO",
                            ICAO = "KSFO",
                            Latitude = 37.6188,
                            Longitude = -122.375,
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            AirportId = new Guid("22585730-68ca-4ff4-aee6-100ba0244c06"),
                            AirportName = "Seattle-Tacoma International Airport",
                            Altitude = 433.0,
                            City = "Seattle",
                            Country = "United States",
                            DST = "A",
                            IATA = "SEA",
                            ICAO = "KSEA",
                            Latitude = 47.450200000000002,
                            Longitude = -122.30880000000001,
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            AirportId = new Guid("84039810-bab3-47d9-a8e5-ac0d53d9c48b"),
                            AirportName = "Miami International Airport",
                            Altitude = 8.0,
                            City = "Miami",
                            Country = "United States",
                            DST = "A",
                            IATA = "MIA",
                            ICAO = "KMIA",
                            Latitude = 25.7959,
                            Longitude = -80.287000000000006,
                            Timezone = "America/New_York"
                        },
                        new
                        {
                            AirportId = new Guid("3874ed80-24b8-4a14-9427-af38c0245a40"),
                            AirportName = "Heathrow Airport",
                            Altitude = 83.0,
                            City = "London",
                            Country = "United Kingdom",
                            DST = "E",
                            IATA = "LHR",
                            ICAO = "EGLL",
                            Latitude = 51.470599999999997,
                            Longitude = -0.46189999999999998,
                            Timezone = "Europe/London"
                        },
                        new
                        {
                            AirportId = new Guid("53016a72-5a18-4d6b-9dd7-45033ae5b56d"),
                            AirportName = "Charles de Gaulle Airport",
                            Altitude = 392.0,
                            City = "Paris",
                            Country = "France",
                            DST = "E",
                            IATA = "CDG",
                            ICAO = "LFPG",
                            Latitude = 49.009700000000002,
                            Longitude = 2.5478999999999998,
                            Timezone = "Europe/Paris"
                        },
                        new
                        {
                            AirportId = new Guid("6ac9b3ac-8fc6-4aea-b900-032b630acfc4"),
                            AirportName = "Frankfurt Airport",
                            Altitude = 364.0,
                            City = "Frankfurt",
                            Country = "Germany",
                            DST = "E",
                            IATA = "FRA",
                            ICAO = "EDDF",
                            Latitude = 50.0379,
                            Longitude = 8.5622000000000007,
                            Timezone = "Europe/Berlin"
                        },
                        new
                        {
                            AirportId = new Guid("6ef2424e-94b7-47af-9bfa-25a49c921bd0"),
                            AirportName = "Amsterdam Airport Schiphol",
                            Altitude = -11.0,
                            City = "Amsterdam",
                            Country = "Netherlands",
                            DST = "E",
                            IATA = "AMS",
                            ICAO = "EHAM",
                            Latitude = 52.308599999999998,
                            Longitude = 4.7638999999999996,
                            Timezone = "Europe/Amsterdam"
                        },
                        new
                        {
                            AirportId = new Guid("12ed44b8-9c4b-479a-a555-2b2b5aa27475"),
                            AirportName = "Adolfo Suárez Madrid–Barajas Airport",
                            Altitude = 1998.0,
                            City = "Madrid",
                            Country = "Spain",
                            DST = "E",
                            IATA = "MAD",
                            ICAO = "LEMD",
                            Latitude = 40.471899999999998,
                            Longitude = -3.5626000000000002,
                            Timezone = "Europe/Madrid"
                        },
                        new
                        {
                            AirportId = new Guid("c4169483-a26d-4784-9518-07a46c8da8e4"),
                            AirportName = "Leonardo da Vinci–Fiumicino Airport",
                            Altitude = 13.0,
                            City = "Rome",
                            Country = "Italy",
                            DST = "E",
                            IATA = "FCO",
                            ICAO = "LIRF",
                            Latitude = 41.8003,
                            Longitude = 12.238899999999999,
                            Timezone = "Europe/Rome"
                        },
                        new
                        {
                            AirportId = new Guid("c7924d51-ecaf-4c5a-8c71-1e12c6bf4768"),
                            AirportName = "Munich Airport",
                            Altitude = 1487.0,
                            City = "Munich",
                            Country = "Germany",
                            DST = "E",
                            IATA = "MUC",
                            ICAO = "EDDM",
                            Latitude = 48.3538,
                            Longitude = 11.786099999999999,
                            Timezone = "Europe/Berlin"
                        },
                        new
                        {
                            AirportId = new Guid("86baeade-ee30-40fd-bb2b-7b9008a73287"),
                            AirportName = "Barcelona–El Prat Airport",
                            Altitude = 12.0,
                            City = "Barcelona",
                            Country = "Spain",
                            DST = "E",
                            IATA = "BCN",
                            ICAO = "LEBL",
                            Latitude = 41.297400000000003,
                            Longitude = 2.0832999999999999,
                            Timezone = "Europe/Madrid"
                        },
                        new
                        {
                            AirportId = new Guid("ffd6d433-d834-4192-ab2c-cc42b4da5460"),
                            AirportName = "Istanbul Airport",
                            Altitude = 325.0,
                            City = "Istanbul",
                            Country = "Turkey",
                            DST = "E",
                            IATA = "IST",
                            ICAO = "LTFM",
                            Latitude = 41.275300000000001,
                            Longitude = 28.751899999999999,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            AirportId = new Guid("b904dc06-aab7-475d-b7d8-3485bcd9541b"),
                            AirportName = "Zurich Airport",
                            Altitude = 1416.0,
                            City = "Zurich",
                            Country = "Switzerland",
                            DST = "E",
                            IATA = "ZRH",
                            ICAO = "LSZH",
                            Latitude = 47.464700000000001,
                            Longitude = 8.5492000000000008,
                            Timezone = "Europe/Zurich"
                        },
                        new
                        {
                            AirportId = new Guid("55c74bf0-41f4-4b89-9abf-cd1101aaa1b3"),
                            AirportName = "Warsaw Chopin Airport",
                            Altitude = 362.0,
                            City = "Warsaw",
                            Country = "Poland",
                            DST = "E",
                            IATA = "WAW",
                            ICAO = "EPWA",
                            Latitude = 52.165700000000001,
                            Longitude = 20.967099999999999,
                            Timezone = "Europe/Warsaw"
                        },
                        new
                        {
                            AirportId = new Guid("0dfa908f-fb37-4cfc-8942-b4ca4374457d"),
                            AirportName = "John Paul II International Airport Kraków–Balice",
                            Altitude = 791.0,
                            City = "Kraków",
                            Country = "Poland",
                            DST = "E",
                            IATA = "KRK",
                            ICAO = "EPKK",
                            Latitude = 50.0777,
                            Longitude = 19.784800000000001,
                            Timezone = "Europe/Warsaw"
                        });
                });

            modelBuilder.Entity("FLyTicketService.Model.AircraftSeat", b =>
                {
                    b.HasOne("FLyTicketService.Model.Aircraft", "Aircraft")
                        .WithMany("Seats")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FLyTicketService.Model.Aircraft", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
